// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hhqerjxkptknwudsnlgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_64AtuXy469nIF-4h-oLvKQ_SV9o41Kl";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
